const ENV = {
  api: 'http://xb1.handsight.cn:8099/ad',
  showTime: 8,
  typeData: [
    {
      typeId: 1,
      adType: '飞机',
      text: '飞机',
      value: '飞机',
    },
    {
      typeId: 2,
      adType: '自行车',
      text: '自行车',
      value: '自行车',
    },
    {
      typeId: 3,
      adType: '鸟',
      text: '鸟',
      value: '鸟',
    },
    {
      typeId: 4,
      adType: '船',
      text: '船',
      value: '船',
    },
    {
      typeId: 5,
      adType: '瓶子',
      text: '瓶子',
      value: '瓶子',
    },
    {
      typeId: 6,
      adType: '公共汽车',
      text: '公共汽车',
      value: '公共汽车',
    },
    {
      typeId: 7,
      adType: '轿车',
      text: '轿车',
      value: '轿车',
    },
    {
      typeId: 8,
      adType: '猫',
      text: '猫',
      value: '猫',
    },
    {
      typeId: 9,
      adType: '椅子',
      text: '椅子',
      value: '椅子',
    },
    {
      typeId: 10,
      adType: '牛',
      text: '牛',
      value: '牛',
    },
    {
      typeId: 11,
      adType: '餐桌',
      text: '餐桌',
      value: '餐桌',
    },
    {
      typeId: 12,
      adType: '狗',
      text: '狗',
      value: '狗',
    },
    {
      typeId: 13,
      adType: '马',
      text: '马',
      value: '马',
    },
    {
      typeId: 14,
      adType: '摩托车',
      text: '摩托车',
      value: '摩托车',
    },
    {
      typeId: 15,
      adType: '人',
      text: '人',
      value: '人',
    },
    {
      typeId: 16,
      adType: '盆栽',
      text: '盆栽',
      value: '盆栽',
    },
    {
      typeId: 17,
      adType: '绵羊',
      text: '绵羊',
      value: '绵羊',
    },
    {
      typeId: 18,
      adType: '沙发',
      text: '沙发',
      value: '沙发',
    },
    {
      typeId: 19,
      adType: '火车',
      text: '火车',
      value: '火车',
    },
    {
      typeId: 20,
      adType: '电视/监视器',
      text: '电视/监视器',
      value: '电视/监视器',
    },
  ],
  adInfo: [
    {
      adId: 1,
      adName: '汽车中的战斗机?',
      adTypeId: 1,
      adType: '汽车',
      adBrandId: 1,
      adBrand: '宝马',
      adContent: '越峥嵘,越从容',
      adImage: 'http://resource.handsight.cn/TVHelp01/img/upload/1477539252155_3395.jpg',
    }, {
     adId: 2,
     adName: '加多宝王老吉哪个正宗?',
     adTypeId: 2,
     adType: '饮料',
     adBrandId: 2,
     adBrand: '加多宝',
     adContent: '凉茶我只喝加多宝',
     adImage: 'http://resource.handsight.cn/TVHelp01/img/upload/1477539252154_8818.jpg',
   },

    {
      adId: 3,
      adName: '宜家家具,简朴不简单?',
      adTypeId: 3,
      adType: '家具',
      adBrandId: 3,
      adBrand: '宜家家具',
      adContent: '宜家家具给你家的感觉',
      adImage: 'http://resource.handsight.cn/TVHelp01/img/upload/1477539252156_3106.jpg',
    },
  ],
}
